version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    docker:
      # - image: cimg/node:lts
      - image: node:latest
    steps:
      - run:
          command: |
            echo "CI is '$CI'" 
            echo "CIRCLE_USERNAME is '$CIRCLE_USERNAME'" 
            echo "CIRCLE_BRANCH is '$CIRCLE_BRANCH'" 
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - run: 
          name: Deployment
          command: |
            echo "CI is '$CI'" 
            echo "CIRCLE_USERNAME is '$CIRCLE_USERNAME'" 
            echo "CIRCLE_BRANCH is '$CIRCLE_BRANCH'" 

workflows:
  build-hold-deploy:
    jobs:
      - build
      - hold: # hold というジョブ名は固定で、メインの設定（上部の jobs 部分）に入れないようにしてください。
          type: approval # 承認ジョブを表示。
          requires:
            - build
      - deploy:
          requires:
            - hold
            
