version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "https://circleci.com/" > /tmp/link.html;
            echo "https://circleci.com/" > /tmp/link.txt;
            echo "[CircleCI Top](https://circleci.com/)" > /tmp/link.md;

      - store_artifacts:
          path: /tmp/link.html

      - store_artifacts:
          path: /tmp/link.md
      
      - store_artifacts:
          path: /tmp/link.txt
