version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    environment:
      JOB_HOME:   src
      CIRCLE_PROJECT_REPONAME: "${CIRCLE_PROJECT_REPONAME}"
      COV_STREAM: "${CIRCLE_PROJECT_REPONAME}_${JOB_HOME}_${CIRCLE_BRANCH}"
    steps:
      - run:
          command: |
            echo ${COV_STREAM}

workflows:
  test_environment_key:
    jobs:
      - build            
