version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "<a href=\"https://circleci.com/\">CircleCI トップページ</a>" > /tmp/link.html;
            echo "https://circleci.com/" > /tmp/link.txt;

      - store_artifacts:
          path: /tmp/link.html

      - store_artifacts:
          path: /tmp/link.txt
