version: 2.1
jobs:
  build:
    docker:
      - image: python:3.6.3-jessie

    working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "https://circleci.com/" > /tmp/link.txt;

      - store_artifacts:
          path: /tmp/link.txt
